
from graph_class import Graph

if __name__ == "__main__":

    g1 = Graph()
    print(f"Graph g1 has id {id(g1)}")
    g1.add_edge(('a', 'b'))
    g1.add_edge(('a','d'))  
    g1.add_edge(('b','d'))  
    g1.add_edge(('b','e'))  
    g1.add_edge(('c','e'))  
    print(f"g1 edges:\n{g1.show_edges()}")
    print(f"g1.nodes: {g1.nodes}")
    print()
    print(f"find_path('d', 'c'): {g1.find_path('d', 'c')}")
    print(f"find_path('c', 'd'): {g1.find_path('c', 'd')}")
    print(f"find_paths('c', 'd'): {g1.find_paths('c', 'd')}")
    print(f"find_paths('a', 'c'): {g1.find_paths('a', 'c')}")
    print(f"shortest_path(): {g1.shortest_path()}")
    print(f"longest_path(): {g1.longest_path()}")
    print(f"Hamiltonian?: {g1.hamiltonian()}")
    print()
    
    g2 = Graph()
    print(f"Graph g2 has id {id(g2)}")
    g2.add_edge(('a','c'))
    g2.add_edge(('a','d'))  
    g2.add_edge(('b','d'))  
    g2.add_edge(('b','e'))  
    g2.add_edge(('c','e'))
    print(f"g2 edges: {g2.show_edges()}")
    print(f"g2.nodes: {g2.nodes}")
    print(f"g2.graph: {g2.graph}")
    print()
    print(f"find_path('d', 'c'): {g2.find_path('d', 'c')}")
    print(f"find_path('c', 'd'): {g2.find_path('c', 'd')}")
    print(f"Hamiltonian?: {g2.hamiltonian()}")
    print()

    g3 = Graph()
    print(f"Graph g3 has id {id(g3)}")
    g3.add_edge(('a','b'))
    g3.add_edge(('b','c'))  
    g3.add_edge(('d','e'))  
    g3.add_edge(('c','d'))
    print(f"g3 edges: {g3.show_edges()}")
    print(f"g3.nodes: {g3.nodes}")
    print(f"g3.graph: {g3.graph}")
    print()
    print(f"find_path('d', 'c'): {g3.find_path('d', 'c')}")
    print(f"find_path('c', 'd'): {g3.find_path('c', 'd')}")
    print(f"find_path('a', 'd'): {g3.find_path('a', 'd')}")
    print(f"find_path('d', 'a'): {g3.find_path('d', 'a')}")
    print(f"Hamiltonian?: {g3.hamiltonian()}")
    print()
    
    g4 = Graph()
    print(f"Graph g4 has id {id(g4)}")
    g4.add_edge(('a','b'))
    g4.add_edge(('b','d'))  
    g4.add_edge(('c','e'))
    print(f"g4 edges: {g4.show_edges()}")
    print(f"g4.nodes: {g4.nodes}")
    print(f"g4.graph: {g4.graph}")
    print()
    print(f"find_all_paths(): {g4.find_all_paths()}")
    print(f"shortest: {g4.shortest_path()}")
    print(f"longtest: {g4.longest_path()}")
    
    print(f"Hamiltonian?: {g4.hamiltonian()}")
    print()
    
    g5 = Graph()
    print(f"Graph g5 has id {id(g5)}")
    g5.add_edge(('a','b'))
    g5.add_edge(('a','c'))
    g5.add_edge(('a','d'))
    g5.add_edge(('a','e'))  
    g5.add_edge(('b','c'))
    g5.add_edge(('c','e'))
    g5.add_edge(('d','e'))
    print(f"g5 edges: {g5.show_edges()}")
    print(f"g5.nodes: {g5.nodes}")
    print(f"g5.graph: {g5.graph}")
    print()
    print(f"find_paths('b', 'e'): {g5.find_paths('b', 'e')}")
    print(f"find_paths('c', 'a'): {g5.find_paths('c', 'a')}")
    print()
    print(f"find_all_paths(): {g5.find_all_paths()}")
    print(f"shortest_path(): {g5.shortest_path()}")
    print(f"longest_path(): {g5.longest_path()}")
    print(f"Hamiltonian?: {g5.hamiltonian()}")
    print()
    
    g6 = Graph()
    print(f"Graph g6 has id {id(g6)}")
    g6.add_edge(('a','b'))
    g6.add_edge(('b','c'))
    g6.add_edge(('c','d'))
    print(f"g6 edges: {g6.show_edges()}")
    print(f"g6.nodes: {g6.nodes}")
    print(f"g6.graph: {g6.graph}")
    print()
    print(f"find_paths('b', 'a'): {g6.find_paths('b', 'a')}")
    print(f"find_paths('a', 'd'): {g6.find_paths('c', 'd')}")
    print()
    print(f"shortest_path(): {g6.shortest_path()}")
    print(f"longest_path(): {g6.longest_path()}")
    print(f"Hamiltonian?: {g6.hamiltonian()}")
   